package manifest

// openapi_scaffold.go — materializes a PORTABLE manifest from an OpenAPI 3.x
// document for `labctl catalog add --openapi`. This is a MATERIALIZE approach
// (a deliberate design choice): the spec is parsed once at add-time and its
// operations/auth are written out as concrete commands:/auth: in the manifest.
// labctl does NOT vendor the spec file and does NOT emit a `spec:` reference —
// the installed catalog manifest stands alone, like any other portable
// manifest.
//
// It reuses spec.go's libopenapi inference (parseOperations/buildCommands) for
// the command set rather than re-walking the document, and adds auth-strategy
// inference from components.securitySchemes on top, since `spec:` inference
// (InferredCommands) only ever derived commands — it never had to choose an
// auth: block, because a `spec:`-based service still declares auth: by hand.

import (
	"fmt"
	"net/url"
	"sort"
	"strings"

	v3 "github.com/pb33f/libopenapi/datamodel/high/v3"
	"gopkg.in/yaml.v3"
)

// GenerateManifestFromSpec parses specBytes as an OpenAPI 3.x document and
// returns a portable manifest's YAML bytes for a service named name: no
// base_url, no spec:, no secret ref — commands: are materialized concretely
// from the document's operations, and auth: is inferred from
// components.securitySchemes on a best-effort basis (see inferAuth). The
// result is validated via ValidatePortableManifest before being returned, so a
// caller never receives a manifest that would fail the same gate
// `catalog add <dir>` applies to every manifest.
func GenerateManifestFromSpec(name string, specBytes []byte) ([]byte, error) {
	// Parse the document exactly once and thread it through operation
	// extraction, auth-scheme inference, and info extraction below, rather
	// than re-parsing the same bytes per extraction step.
	doc, err := buildV3Document(specBytes)
	if err != nil {
		return nil, err
	}

	ops := operationsFromDoc(doc)
	if err := checkCommandKeyUniqueness(ops); err != nil {
		return nil, err
	}
	cmds := buildCommands(ops, SpecFilter{})

	prefix := envPrefix(name)
	desc := openapiDescription(doc, name)
	mapping := inferAuth(doc)

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — labctl service manifest, generated from an OpenAPI document.\n", name)
	b.WriteString("#\n")
	b.WriteString("# Generated by `labctl catalog add --openapi`. This is a PORTABLE manifest: no\n")
	b.WriteString("# base_url, no spec:, no secret ref — bind those in profile.yaml. Review the\n")
	b.WriteString("# auth: block below (and any comments) before using this service.\n\n")
	if err := writeYAMLField(&b, "name", name); err != nil {
		return nil, fmt.Errorf("marshal name: %w", err)
	}
	if err := writeYAMLField(&b, "description", desc); err != nil {
		return nil, fmt.Errorf("marshal description: %w", err)
	}
	b.WriteByte('\n')
	if err := writeYAMLField(&b, "env_prefix", prefix); err != nil {
		return nil, fmt.Errorf("marshal env_prefix: %w", err)
	}

	b.WriteString("\n# --- Authentication ------------------------------------------------------\n")
	if mapping.comment != "" {
		writeWrappedComment(&b, mapping.comment)
	}
	if err := writeYAMLField(&b, "auth", mapping.authValue()); err != nil {
		return nil, fmt.Errorf("marshal auth: %w", err)
	}
	if len(mapping.secrets) > 0 {
		secrets := append([]secret(nil), mapping.secrets...)
		sort.Slice(secrets, func(i, j int) bool { return secrets[i].name < secrets[j].name })
		b.WriteString("\nsecrets:\n")
		b.WriteString("  # A secret is a reference, never a literal value — labctl resolves it at\n")
		b.WriteString("  # call time via the configured provider. This manifest only DECLARES each\n")
		b.WriteString("  # slot; bind the ref: per machine in profile.yaml.\n")
		for _, s := range secrets {
			fmt.Fprintf(&b, "  %s:\n    env: %s_%s            # optional env override for CI\n", s.name, prefix, strings.ToUpper(s.name))
		}
	}

	b.WriteString("\n# --- Commands (inferred from the OpenAPI document) ------------------------\n")
	if err := writeYAMLField(&b, "commands", commandsValue(cmds)); err != nil {
		return nil, fmt.Errorf("marshal commands: %w", err)
	}

	out := []byte(b.String())
	if _, err := ValidatePortableManifest(out); err != nil {
		return nil, fmt.Errorf("generated manifest failed validation (this is a labctl bug, please report it): %w\n---\n%s", err, out)
	}
	return out, nil
}

// InferServiceName derives a candidate service/catalog name from the OpenAPI
// document's info.title, slugified to the same shape catalog names require
// (^[a-z0-9][a-z0-9_-]*$ — see ValidateCatalogName). Returns "", nil if the
// document declares no title; the caller (catalog add --openapi) treats that
// as "pass --name". The returned name is NOT guaranteed to pass
// ValidateCatalogName (e.g. a title that slugifies to "" or to a name starting
// with a character ValidateCatalogName still rejects) — the caller validates it.
func InferServiceName(specBytes []byte) (string, error) {
	doc, err := buildV3Document(specBytes)
	if err != nil {
		return "", err
	}
	if doc == nil || doc.Info == nil || strings.TrimSpace(doc.Info.Title) == "" {
		return "", nil
	}
	return slugify(doc.Info.Title), nil
}

// checkCommandKeyUniqueness recomputes commandKey for every operation and
// errors if two distinct operations would collide on the same key — buildCommands
// stores commands in a map keyed by commandKey, so a silent collision would drop
// one operation's command without any indication. Also rejects an operation
// that produces an empty key (a degenerate operationId/method/path).
func checkCommandKeyUniqueness(ops []specOp) error {
	seen := make(map[string]string, len(ops)) // command key -> the operation that claimed it
	for _, op := range ops {
		key := commandKey(op)
		ident := op.Method + " " + op.Path
		if op.OperationID != "" {
			ident = fmt.Sprintf("%s (operationId %q)", ident, op.OperationID)
		}
		if key == "" {
			return &ConfigError{Err: fmt.Errorf("operation %s produced an empty command key (operationId/path too degenerate to slugify)", ident)}
		}
		if prev, dup := seen[key]; dup {
			return &ConfigError{Err: fmt.Errorf("operations %q and %q both generate the command key %q; give the OpenAPI document unique operationIds (or filter one out) before adding it as a catalog", prev, ident, key)}
		}
		seen[key] = ident
	}
	return nil
}

// commandsValue converts inferred commands into a plain map[string]any keyed
// the same as the source map, with only the fields buildCommands actually
// populates (help/method/path) — so the generated YAML stays as clean as a
// hand-authored scaffold rather than spelling out every zero-valued Command
// field (query/headers/body/codec/…) that struct-marshaling Command directly
// would emit.
func commandsValue(cmds map[string]Command) map[string]any {
	out := make(map[string]any, len(cmds))
	for key, c := range cmds {
		v := map[string]any{
			"method": c.Method,
			"path":   c.Path,
		}
		if c.Help != "" {
			v["help"] = c.Help
		}
		out[key] = v
	}
	return out
}

// openapiAuthMapping is the auth: strategy GenerateManifestFromSpec infers (or
// the graceful "none" fallback) for an OpenAPI document, plus the secret slots
// it declares and an optional explanatory comment.
type openapiAuthMapping struct {
	strategy string   // none|header-key|bearer|basic|oauth2-client-credentials
	header   string   // header-key: header name
	tokenURL string   // oauth2-client-credentials: token endpoint (real or placeholder)
	secrets  []secret // declared secret slots (reuses scaffold.go's (name, op-field) pair)
	comment  string   // explanatory comment shown above auth: (sanitized, word-wrapped on write)
}

// authValue returns the auth: block as a plain map[string]any (only the fields
// the strategy uses), so yaml.Marshal both quotes/escapes every value safely
// (header names and similar come from the OpenAPI document, which is untrusted
// input) and omits the irrelevant fields a raw Auth-struct marshal would emit.
func (m openapiAuthMapping) authValue() map[string]any {
	switch m.strategy {
	case "header-key":
		return map[string]any{
			"strategy": "header-key",
			"header":   m.header,
			"value":    "{secret.api_key}",
		}
	case "bearer":
		return map[string]any{
			"strategy": "bearer",
			"scheme":   "Bearer",
			"value":    "{secret.token}",
		}
	case "basic":
		return map[string]any{
			"strategy": "basic",
			"username": "{secret.username}",
			"password": "{secret.password}",
		}
	case "oauth2-client-credentials":
		return map[string]any{
			"strategy":      "oauth2-client-credentials",
			"token_url":     m.tokenURL,
			"client_id":     "{secret.client_id}",
			"client_secret": "{secret.client_secret}",
		}
	default:
		return map[string]any{"strategy": "none"}
	}
}

// inferAuth picks one auth strategy from doc's security schemes (best-effort)
// or falls back to {strategy: none} with a comment explaining what it found and
// that the user must finish wiring auth by hand. doc may be nil (an OpenAPI
// document that parsed to no model).
func inferAuth(doc *v3.Document) openapiAuthMapping {
	if doc == nil || doc.Components == nil || doc.Components.SecuritySchemes == nil || doc.Components.SecuritySchemes.Len() == 0 {
		return openapiAuthMapping{
			strategy: "none",
			comment:  "OpenAPI document declares no components.securitySchemes; wire auth manually.",
		}
	}
	name, scheme := selectSecurityScheme(doc)
	if scheme == nil {
		return openapiAuthMapping{
			strategy: "none",
			comment:  "OpenAPI document declares no components.securitySchemes; wire auth manually.",
		}
	}
	return mapSecurityScheme(name, scheme)
}

// selectSecurityScheme picks the security scheme to base auth: on: the first
// scheme named by the document's global `security` requirement, if any;
// otherwise the first scheme declared in components.securitySchemes (in
// document order — deterministic for a given document either way).
func selectSecurityScheme(doc *v3.Document) (string, *v3.SecurityScheme) {
	schemes := doc.Components.SecuritySchemes
	if name := firstGlobalSecurityScheme(doc); name != "" {
		if s, ok := schemes.Get(name); ok && s != nil {
			return name, s
		}
	}
	for name, s := range schemes.FromOldest() {
		return name, s
	}
	return "", nil
}

// firstGlobalSecurityScheme returns the first scheme name referenced by doc's
// top-level `security` requirements (in document order), or "" if doc declares
// none (or only empty/optional requirements).
func firstGlobalSecurityScheme(doc *v3.Document) string {
	for _, req := range doc.Security {
		if req == nil || req.Requirements == nil {
			continue
		}
		for name := range req.Requirements.FromOldest() {
			return name
		}
	}
	return ""
}

// mapSecurityScheme maps one OpenAPI security scheme to an auth: strategy.
// Anything it cannot faithfully map (apiKey in query/cookie, an oauth2 scheme
// with no clientCredentials flow, openIdConnect, mutualTLS, or an unrecognized
// type) falls back to {strategy: none} plus a comment explaining why — never a
// bogus mapping (e.g. never wires a query/cookie key into header-key auth).
func mapSecurityScheme(name string, s *v3.SecurityScheme) openapiAuthMapping {
	switch strings.ToLower(s.Type) {
	case "apikey":
		if strings.EqualFold(s.In, "header") {
			header := s.Name
			if strings.TrimSpace(header) == "" {
				header = "X-Api-Key"
			}
			return openapiAuthMapping{
				strategy: "header-key",
				header:   header,
				secrets:  []secret{{"api_key", "FIELD"}},
			}
		}
		return openapiAuthMapping{
			strategy: "none",
			comment: fmt.Sprintf("OpenAPI declared an apiKey security scheme %q with in: %s; labctl has no %s-key auth strategy (only header) — wire this manually, e.g. as a query param in each command's `query:` template.",
				sanitizeForComment(name), sanitizeForComment(s.In), sanitizeForComment(s.In)),
		}
	case "http":
		switch strings.ToLower(s.Scheme) {
		case "bearer":
			return openapiAuthMapping{
				strategy: "bearer",
				secrets:  []secret{{"token", "FIELD"}},
			}
		case "basic":
			return openapiAuthMapping{
				strategy: "basic",
				secrets:  []secret{{"username", "FIELD"}, {"password", "FIELD"}},
			}
		default:
			return openapiAuthMapping{
				strategy: "none",
				comment: fmt.Sprintf("OpenAPI declared an http security scheme %q with scheme: %q; labctl has no auth strategy for it (only bearer and basic) — wire this manually.",
					sanitizeForComment(name), sanitizeForComment(s.Scheme)),
			}
		}
	case "oauth2":
		if s.Flows != nil && s.Flows.ClientCredentials != nil {
			m := openapiAuthMapping{
				strategy: "oauth2-client-credentials",
				secrets:  []secret{{"client_id", "client_id"}, {"client_secret", "client_secret"}},
			}
			tokenURL := s.Flows.ClientCredentials.TokenUrl
			if isAbsoluteHTTPURL(tokenURL) {
				m.tokenURL = tokenURL
			} else {
				m.tokenURL = "https://CHANGE-ME.example.com/oauth/token"
				m.comment = fmt.Sprintf("OpenAPI's oauth2 clientCredentials flow for security scheme %q did not declare an absolute http(s) tokenUrl (got %q); set token_url below to the real token endpoint before using this service.",
					sanitizeForComment(name), sanitizeForComment(tokenURL))
			}
			return m
		}
		return openapiAuthMapping{
			strategy: "none",
			comment: fmt.Sprintf("OpenAPI declared an oauth2 security scheme %q with flows [%s] but no clientCredentials flow; labctl's oauth2 support is client-credentials only — wire this manually.",
				sanitizeForComment(name), oauthFlowNames(s.Flows)),
		}
	case "openidconnect":
		return openapiAuthMapping{
			strategy: "none",
			comment:  fmt.Sprintf("OpenAPI declared an openIdConnect security scheme %q; labctl has no openIdConnect auth strategy — wire this manually.", sanitizeForComment(name)),
		}
	case "mutualtls":
		return openapiAuthMapping{
			strategy: "none",
			comment:  fmt.Sprintf("OpenAPI declared a mutualTLS security scheme %q; labctl has no client-certificate auth strategy — wire this manually.", sanitizeForComment(name)),
		}
	default:
		return openapiAuthMapping{
			strategy: "none",
			comment:  fmt.Sprintf("OpenAPI declared a security scheme %q of unrecognized type %q; wire auth manually.", sanitizeForComment(name), sanitizeForComment(s.Type)),
		}
	}
}

// oauthFlowNames lists the OAuth2 flows an OAuthFlows declares (for a
// diagnostic comment), or "none" if flows is nil or empty.
func oauthFlowNames(flows *v3.OAuthFlows) string {
	if flows == nil {
		return "none"
	}
	var names []string
	if flows.Implicit != nil {
		names = append(names, "implicit")
	}
	if flows.Password != nil {
		names = append(names, "password")
	}
	if flows.AuthorizationCode != nil {
		names = append(names, "authorizationCode")
	}
	if flows.Device != nil {
		names = append(names, "device")
	}
	if len(names) == 0 {
		return "none"
	}
	return strings.Join(names, ", ")
}

// isAbsoluteHTTPURL reports whether s parses as an absolute http(s) URL with a
// host — used to decide whether an oauth2 clientCredentials tokenUrl is usable
// as-is or needs a placeholder + comment.
func isAbsoluteHTTPURL(s string) bool {
	if strings.TrimSpace(s) == "" {
		return false
	}
	u, err := url.Parse(s)
	if err != nil {
		return false
	}
	return (u.Scheme == "http" || u.Scheme == "https") && u.Host != ""
}

// openapiDescription builds the manifest's description: from the document's
// info.title (falling back to "<name> service" when absent) plus the first
// line of info.description, if any and distinct from the title.
func openapiDescription(doc *v3.Document, fallbackName string) string {
	fallback := fallbackName + " service"
	if doc == nil || doc.Info == nil {
		return fallback
	}
	title := strings.TrimSpace(doc.Info.Title)
	if title == "" {
		title = fallback
	}
	first := firstLine(doc.Info.Description, 160)
	if first == "" || strings.EqualFold(first, title) {
		return title
	}
	return title + " — " + first
}

// firstLine returns the first non-empty line of s, truncated to max runes
// (with an ellipsis) if longer, and with internal whitespace collapsed.
func firstLine(s string, max int) string {
	for _, line := range strings.Split(s, "\n") {
		line = sanitizeForComment(line)
		if line == "" {
			continue
		}
		r := []rune(line)
		if len(r) > max {
			return string(r[:max]) + "…"
		}
		return line
	}
	return ""
}

// sanitizeForComment collapses a string to a single line of whitespace-
// normalized text, safe to embed in a `#` YAML comment or interpolate into one
// — OpenAPI document content (titles, scheme names, descriptions) is untrusted
// input and may contain newlines or other control characters.
func sanitizeForComment(s string) string {
	s = strings.Map(func(r rune) rune {
		if r == '\n' || r == '\r' || r == '\t' {
			return ' '
		}
		return r
	}, s)
	return strings.TrimSpace(strings.Join(strings.Fields(s), " "))
}

// writeWrappedComment writes text as one or more "# "-prefixed comment lines,
// word-wrapped to a readable width.
func writeWrappedComment(b *strings.Builder, text string) {
	const width = 78
	words := strings.Fields(sanitizeForComment(text))
	if len(words) == 0 {
		return
	}
	line := "#"
	for _, w := range words {
		if len(line)+1+len(w) > width && line != "#" {
			b.WriteString(line)
			b.WriteByte('\n')
			line = "#"
		}
		line += " " + w
	}
	b.WriteString(line)
	b.WriteString("\n\n")
}

// writeYAMLField marshals map[string]any{key: value} and appends it to b. Using
// yaml.Marshal (rather than hand-built text) for every field that may carry
// untrusted OpenAPI-document content (header names, descriptions, tokenUrl,
// …) guarantees correct YAML quoting/escaping — a hand-written "key: value"
// line would need to reimplement that escaping itself to stay safe. The
// encoder is pinned to 2-space indent to match the hand-written style the rest
// of the codebase (scaffold.go, the embedded catalog) uses, rather than
// yaml.Marshal's 4-space default.
func writeYAMLField(b *strings.Builder, key string, value any) error {
	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(map[string]any{key: value}); err != nil {
		_ = enc.Close()
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}
	b.WriteString(buf.String())
	return nil
}
