{{- if .Values.auth.onePasswordItem.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "labctl-mcp.fullname" . }}-op-token
  labels:
    {{- include "labctl-mcp.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.auth.onePasswordItem.itemPath | quote }}
{{- end }}
{{- if and .Values.mcp.auth.enabled .Values.mcp.auth.onePasswordItem.itemPath }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "labctl-mcp.fullname" . }}-mcp-auth-token
  labels:
    {{- include "labctl-mcp.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.mcp.auth.onePasswordItem.itemPath | quote }}
{{- end }}
